esphome:
  name: tensione
  friendly_name: Tensione

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:
  encryption:
    key: "lG2fhkorpoczyIPwitwJ5IZUhyqqUrV/mN/wNcloyJs="

ota:
  - platform: esphome
    password: "43f01c7b641c48280ae959bdd2de34e9"

captive_portal:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Tensione Fallback Hotspot"
    password: "nHucmfVko2Ii"

sensor:
  - platform: adc
    pin: GPIO34
    name: "Tensione Ingresso"
    id: input_voltage
    unit_of_measurement: "V"
    icon: "mdi:flash"
    attenuation: 11db
    update_interval: 1s
    accuracy_decimals: 2
    filters:
      - multiply: 5.0